import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, ArrowDown, Check, Zap, AlertTriangle, ShieldCheck } from 'lucide-react';
import { ThemeMode } from '../types';

interface RecommendationsTimelineProps {
  theme: ThemeMode;
  onApplyRecommendation?: (recId: string) => void;
}

export const RecommendationsTimeline: React.FC<RecommendationsTimelineProps> = ({ theme, onApplyRecommendation }) => {
  const isDark = theme === 'dark';

  const TIMELINE_STEPS = [
    {
      id: 'rec-mcp',
      timeLabel: 'Priority Action #1',
      actionTitle: 'Add Model Context Protocol (MCP) & Agent Runtime Module',
      targetCourse: 'CS-5090 Cloud Computing & Serverless Architecture',
      impact: '+14% Alignment Boost',
      confidence: 98,
      priority: 'High',
      description: 'Current syllabus focuses on legacy REST controllers. Hiring market shows 340% surge in MCP and multi-agent orchestration.',
      concreteStep: 'Insert 2-week practical lab on MCP server TypeScript primitives & Anthropic SDK.'
    },
    {
      id: 'rec-hadoop',
      timeLabel: 'Priority Action #2',
      actionTitle: 'Replace Legacy MapReduce / Hadoop with Vector Search & Milvus',
      targetCourse: 'CS-4080 Database Systems & Distributed Storage',
      impact: '+18% Alignment Boost',
      confidence: 96,
      priority: 'High',
      description: 'MapReduce occupies 3 weeks of lectures. Modern database infrastructure demands pgvector, Milvus, and HNSW index tuning.',
      concreteStep: 'Update Unit 4 labs to vector search indexing & hybrid sparse/dense retrieval.'
    },
    {
      id: 'rec-k8s',
      timeLabel: 'Priority Action #3',
      actionTitle: 'Add Kubernetes 1.30 Container Orchestration Lab',
      targetCourse: 'CS-3010 Operating Systems & Linux Kernel',
      impact: '+10% Alignment Boost',
      confidence: 94,
      priority: 'Medium',
      description: 'Course covers raw C system calls. Enterprise Cloud Native computing requires container namespaces & CNI networking.',
      concreteStep: 'Add 1-week hands-on lab on minikube, cgroups, and eBPF kernel tracing.'
    },
    {
      id: 'rec-vllm',
      timeLabel: 'Priority Action #4',
      actionTitle: 'Introduce Vector Search & vLLM Memory Management',
      targetCourse: 'CS-8042 Advanced Machine Learning & MLOps',
      impact: '+12% Alignment Boost',
      confidence: 95,
      priority: 'High',
      description: 'Syllabus covers basic PyTorch inference. MLOps roles require vLLM, PagedAttention, and FlashAttention-3 memory optimizations.',
      concreteStep: 'Integrate vLLM multi-GPU inference benchmark assignment.'
    }
  ];

  return (
    <div className={`rounded-[24px] border p-6 sm:p-8 space-y-6 transition-all ${
      isDark ? 'bg-[#111111] border-[#262626]' : 'bg-[#FFFFFF] border-[#E5E7EB] shadow-lg'
    }`}>
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b pb-4 border-[#262626]/40">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-mono font-semibold bg-[#10B981]/15 text-[#10B981] mb-2">
            <Sparkles className="w-3.5 h-3.5" />
            <span>AI Modernization Roadmap</span>
          </div>
          <h2 className="font-heading font-bold text-2xl tracking-tight">Recommendation Execution Timeline</h2>
          <p className={`text-xs mt-1 ${isDark ? 'text-[#B3B3B3]' : 'text-[#6B7280]'}`}>
            Prioritized modernization sequence generated by AI to maximize curriculum health with minimal faculty friction.
          </p>
        </div>

        <span className="px-3 py-1.5 rounded-xl text-xs font-mono font-bold bg-[#10B981]/20 text-[#10B981]">
          4 Actions Ready to Apply
        </span>
      </div>

      {/* Timeline Sequence */}
      <div className="relative pl-6 sm:pl-8 space-y-8 before:absolute before:left-3 sm:before:left-4 before:top-3 before:bottom-3 before:w-0.5 before:bg-[#10B981]/30">
        {TIMELINE_STEPS.map((step, idx) => (
          <motion.div
            key={step.id}
            initial={{ opacity: 0, x: -12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: idx * 0.08 }}
            className="relative space-y-3"
          >
            {/* Timeline Dot Indicator */}
            <div className="absolute -left-6 sm:-left-8 top-1 w-6 h-6 rounded-full bg-[#10B981] text-white flex items-center justify-center font-mono font-bold text-xs shadow-md shadow-[#10B981]/30">
              {idx + 1}
            </div>

            <div className={`p-5 rounded-[20px] border space-y-3 transition-all ${
              isDark ? 'bg-[#171717] border-[#262626]' : 'bg-[#F8FAFC] border-[#E5E7EB] shadow-sm'
            }`}>
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-mono font-bold text-[#10B981]">
                    {step.timeLabel}
                  </span>
                  <span className={`text-[10px] font-mono px-2 py-0.5 rounded border ${
                    isDark ? 'bg-[#0E0E0E] border-[#262626] text-[#B3B3B3]' : 'bg-[#FFFFFF] border-[#E5E7EB] text-[#6B7280]'
                  }`}>
                    {step.targetCourse}
                  </span>
                </div>

                <div className="flex items-center gap-2 text-xs font-mono">
                  <span className="text-amber-400 font-bold">{step.priority} Priority</span>
                  <span className="text-[#10B981] font-bold">{step.impact}</span>
                  <span className={`text-[10px] ${isDark ? 'text-[#737373]' : 'text-[#9CA3AF]'}`}>
                    ({step.confidence}% Confidence)
                  </span>
                </div>
              </div>

              <h3 className="font-heading font-bold text-base">{step.actionTitle}</h3>
              <p className={`text-xs leading-relaxed ${isDark ? 'text-[#B3B3B3]' : 'text-[#6B7280]'}`}>
                {step.description}
              </p>

              <div className={`p-3 rounded-xl border text-xs font-mono flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 ${
                isDark ? 'bg-[#111111] border-[#262626] text-[#34D399]' : 'bg-[#F0FDF4] border-[#BBF7D0] text-[#059669]'
              }`}>
                <span>💡 {step.concreteStep}</span>
                <button
                  onClick={() => onApplyRecommendation?.(step.id)}
                  className="px-3.5 py-1.5 rounded-lg text-xs font-bold text-white bg-[#10B981] hover:bg-[#34D399] transition-all flex items-center gap-1.5 cursor-pointer shadow-sm flex-shrink-0"
                >
                  <Zap className="w-3.5 h-3.5" />
                  <span>1-Click Apply</span>
                </button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
};
